<!-- general -->
<!ENTITY cWater "#b5d0d0">
<!ENTITY cLand "#f2efe9">

<!-- shapefiles -->
<!ENTITY cBuiltup "#dddddd">
<!ENTITY cNeCountriesLine "#808080">
<!ENTITY cNePopulatedName "#808080">

<!-- places -->
<!ENTITY cPlaceName "#9d6c9d">
<!ENTITY cCityName "#000000">
<!ENTITY cCityNameHighZoom "#777777">


<!-- pois -->
<!ENTITY cAccommodationText "#0092DA">
<!ENTITY cAmenityText "#734A08">
<!ENTITY cBarrierText "#666666">
<!ENTITY cEducationText "#39AC39">
<!ENTITY cFoodText "#734A08">
<!ENTITY cHealthText "#DA0092">
<!ENTITY cLanduseText "#999999">
<!ENTITY cMoneyText "#000000">
<!ENTITY cPlaceOfWorshipText "#000000">
<!ENTITY cPowerText "#8e7409">
<!ENTITY cShoppingText "#AC39AC">
<!ENTITY cSportText "#39AC39">
<!ENTITY cTouristText "#734A08">
<!ENTITY cTransportText "#0092DA">
<!ENTITY cWaterText "#0092DA">


<!-- Landcover -->
<!ENTITY cLeisureSwimmingPool "#B5D0D0">
<!ENTITY cLeisureSwimmingPoolOutline "#0000FF">
<!ENTITY cLeisurePlayground "#CCFFF1">
<!ENTITY cLeisurePlaygroundOutline "#666666">
<!ENTITY cLeisurePark "#B6FDB6">
<!ENTITY cLeisureGarden "#CFECA8">

<!ENTITY cTourismCampSite "#CCFF99">
<!ENTITY cTourismCampSiteOutline "#666666">
<!ENTITY cTourismAttraction "#F2CAEA">

<!ENTITY cLanduseQuarry "#808080">
<!ENTITY cLanduseVineyard "#ABDF96">
<!ENTITY cLanduseCemetery "#AACBAF">
<!ENTITY cLanduseResidential "#DDDDDD">
<!ENTITY cLanduseGarages "#999966">
<!ENTITY cLanduseField "#666600">
<!ENTITY cLanduseMeadow "#CFECA8">
<!ENTITY cLanduseField "#666600">
<!ENTITY cLanduseAllotments "#E5C7AB">
<!ENTITY cLanduseForest "#8DC56C">
<!ENTITY cLanduseFarmyard "#DDBF92">
<!ENTITY cLanduseFarm "#EAD8BD">
<!ENTITY cLanduseRecreationGround "#CFECA8">
<!ENTITY cLanduseVillageGreen "#CFECA8">
<!ENTITY cLanduseRetail "#F1DADA">
<!ENTITY cLanduseRetailOutline "#FF0000">
<!ENTITY cLanduseIndustrial "#DFD1D6">
<!ENTITY cLanduseCommercial "#EFC8C8">
<!ENTITY cLanduseBrownfield "#9D9D6C">
<!ENTITY cLanduseConstruction "#9D9D6C">

<!ENTITY cMilitaryBarracks "#FF8F8F">
<!ENTITY cMilitaryDangerArea "#FFC0CB">
<!ENTITY cMilitaryBarracks "#FF8F8F">

<!-- roads -->
<!ENTITY cRoadsText "#000000">
<!ENTITY cBridgeCasing "#000000">

<!-- access -->
<!ENTITY cAccessPermissive "#CCFF99">
<!ENTITY cAccessDestination "#C2E0FF">

<!-- residential -->
<!ENTITY cResidentialCasing "#999999">
<!ENTITY cResidentialFill "#FFFFFF">
<!ENTITY cResidentialConstructionA "#AAAAAA">
<!ENTITY cResidentialConstructionB "#FFFFFF">
