<!-- general -->
<!ENTITY cWater "#b5d0d0">
<!ENTITY cLand "#f2efe9">

<!-- shapefiles -->
<!ENTITY cBuiltup "#dddddd">
<!ENTITY cNeCountriesLine "#808080">
<!ENTITY cNePopulatedName "#808080">

<!-- places -->
<!ENTITY cPlaceName "#9d6c9d">
<!ENTITY cCityName "#000000">
<!ENTITY cCityNameHighZoom "#777777">


<!-- pois -->
<!ENTITY cAccommodationText "#0092DA">
<!ENTITY cAmenityText "#734A08">
<!ENTITY cBarrierText "#666666">
<!ENTITY cEducationText "#39AC39">
<!ENTITY cFoodText "#734A08">
<!ENTITY cHealthText "#DA0092">
<!ENTITY cLanduseText "#999999">
<!ENTITY cMoneyText "#000000">
<!ENTITY cPlaceOfWorshipText "#000000">
<!ENTITY cPowerText "#8e7409">
<!ENTITY cShoppingText "#AC39AC">
<!ENTITY cSportText "#39AC39">
<!ENTITY cTouristText "#734A08">
<!ENTITY cTransportText "#0092DA">
<!ENTITY cWaterText "#0092DA">


<!-- roads -->
<!ENTITY cRoadsText "#000000">
<!ENTITY cBridgeCasing "#000000">

<!-- access -->
<!ENTITY cAccessPermissive "#CCFF99">
<!ENTITY cAccessDestination "#C2E0FF">

<!-- residential -->
<!ENTITY cResidentialCasing "#999999">
<!ENTITY cResidentialFill "#FFFFFF">
<!ENTITY cResidentialConstructionA "#AAAAAA">
<!ENTITY cResidentialConstructionB "#FFFFFF">
