<Style name="pois-accommodation">
	<Rule>
		&maxscale_zoom13;
		<Filter>[tourism]='alpine_hut'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/alpinehut.p.svg" width="16" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='bed_and_breakfast'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/bed_and_breakfast.p.svg" width="20" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[tourism]='camp_site'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/camping.n.svg" width="16" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[tourism]='caravan_site'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/caravan_park.p.svg" width="24" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='chalet'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/chalet.p.svg" width="16" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='hostel' or [tourism]='youth_hostel'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/hostel.p.svg" width="20" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='hotel'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/hotel2.p.svg" width="20" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='motel'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/motel.p.svg" width="20" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[amenity]='shelter'</Filter>
		<PointSymbolizer file="&symbols;/color/accomodation/shelter2.p.svg" width="16" />
	</Rule>
</Style>
