<Style name="pois-accommodation">
	<Rule>
		&maxscale_zoom13;
		<Filter>[tourism]='alpine_hut'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/alpinehut.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='bed_and_breakfast'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/bed_and_breakfast.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[tourism]='camp_site'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/camping.n.png" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[tourism]='caravan_site'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/caravan_park.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='chalet'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/chalet.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='hostel' or [tourism]='youth_hostel'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/hostel.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='hotel'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/hotel2.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='motel'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/motel.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[amenity]='shelter'</Filter>
		<PointSymbolizer file="&symbols;/png/16/accomodation/shelter2.p.png" />
	</Rule>
</Style>
