<Style name="pois-sport">
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='archery'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/archery.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='baseball'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/baseball.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='canoe'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/canoe.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='cricket'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/cricket.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='scuba_diving' or [sport]='diving'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/diving.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='golf'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/golf.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='gym' or [amenity]='gym'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/gym.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='gymnastics'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/gymnasium.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='climbing'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/hillclimbing.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='horse_racing'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/horse_racing.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='skating' or [sport]='ice_skating'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/iceskating.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='leisure' or [sport]='leisure_centre'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/leisure_centre.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='miniature_golf'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/miniature_golf.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='sailing'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/sailing.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='shooting'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/shooting.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='skiing'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/skiing_crosscountry.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='9pin' or [sport]='10pin'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/snooker.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='soccer'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/soccer.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>([sport]='swimming' or [sport]='swimming_pool') and [building] = 'yes'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/swimming_outdoor.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>([sport]='swimming' or [sport]='swimming_pool') and [building] != 'yes'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/swimming_indoor.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='tennis'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/tennis.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='table_tennis'</Filter>
		<!-- need other icon here -->
		<PointSymbolizer file="&symbols;/png/16/sport/tennis.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[sport]='surf' or [sport]='windsurfing' or [sport]='surfing'</Filter>
		<PointSymbolizer file="&symbols;/png/16/sport/windsurfing.p.png" />
	</Rule>
</Style>
