<Style name="pois-tourist">
	<Rule>
		&maxscale_zoom16;
		<Filter>[historic]='archaeological_site'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/archaeological2.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='gallery'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/art_gallery.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[tourism]='attraction'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/attraction.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='artwork'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/attraction.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[historic]='battlefield'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/battlefield.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[natural]='beach'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/beach.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[amenity]='casino'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/casino.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[historic]='castle'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/castle2.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[amenity]='cinema'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/cinema2.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[amenity]='clock'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/clock.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[amenity]='fountain'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/fountain.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom16;
		<Filter>[tourism]='information'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/information.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[historic]='memorial'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/memorial.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[historic]='monument'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/monument.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='museum'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/museum.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='picnic_site'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/picnic.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[historic]='ruins' or [historic]='ruin'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/ruin.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[amenity]='theatre'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/theatre.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='theme_park'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/theme_park.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='viewpoint'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/view_point.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[historic]='wreck'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/wreck.p.png" />
	</Rule>
	<Rule>
		&maxscale_zoom17;
		<Filter>[tourism]='zoo'</Filter>
		<PointSymbolizer file="&symbols;/png/16/tourist/zoo.p.png" />
	</Rule>
	
	
	<Rule>
		<AlsoFilter />
		<TextSymbolizer name="[name]" fontset-name="book-fonts" size="9" fill="&cTouristText;" dy="9" halo-radius="1" wrap-width="0" />
	</Rule>
</Style>
