env = Environment(
    CPPPATH = ['osmium/include', '/usr/include/postgresql/'],
    CXXFLAGS = ['-DOSMIUM_WITH_GEOS'],
)
env.Program(
    'osm-history-importer',
    'importer.cpp',
    LIBS=['expat', 'pq', 'proj', 'z', 'protobuf-lite', 'osmpbf', 'pthread', 'geos'],
)
